name: ci

on:
  pull_request

jobs:
  unit_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: install dependencies
        run: npm install
      
      - name: run unit tests
        run: npm run test
  
  e2e_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: install dependencies
        run: npm install
      
      - name: run e2e tests
        run: npm run e2e:run
  
  build:
    runs-on: ubuntu-22.04
    needs: [unit_tests, e2e_tests]
    permissions: 
      contents: write
      id-token: write
    environment:
      name: staging
      url: ${{env.PUBLIC_URL}}/
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: install dependencies
        run: npm install
      
      - name: set deployment url
        run: echo "PUBLIC_URL=${{vars.PUBLIC_URL}}/${{github.head_ref}}" >> $GITHUB_ENV
      
      - name: run build script
        run: npm run build

      - name: deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: ./build
          target-folder: ${{github.head_ref}}
          clean: false