name: ci

on:
  pull_request

jobs:
  unit_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: install dependencies
        run: npm install
      
      - name: run unit tests
        run: npm run test
  
  e2e_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: install dependencies
        run: npm install
      
      - name: run e2e tests
        run: npm run e2e:run