name: PR Workflow

on: pull_request

jobs:
  UnitTests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm run test

  E2ETests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm run e2e:run

  Build:
    runs-on: ubuntu-22.04
    needs: [UnitTests, E2ETests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm run build

      - name: Rename build
        run: mkdir deploy && mv build deploy/${{github.head_ref}}

      - name: Upload build
        uses: actions/upload-pages-artifact@v1
        with:
          name: ${{github.base_ref}}
          path: "./deploy"

  Deploy:
    runs-on: ubuntu-22.04
    needs: Build
    permissions:
      pages: write
      id-token: write
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          preview: true
          artifact_name: ${{github.base_ref}}
