name: PR Workflow

on: pull_request

jobs:
  UnitTests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Unit tests
        run: npm run test
