name: PR Deployment

on:
    pull_request

jobs:
    UnitTests:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm run test

    E2ETests:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm run e2e:run